export const START_FETCHING_MOVIES= 'START_FETCHING_MOVIES';
export const END_FETCHING_MOVIES= 'END_FETCHING_MOVIES';

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST'; 
export const  REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';

export const START_FETCHING_MOVIE_BY_ID = 'START_FETCHING_MOVIE_BY_ID';
export const END_FETCHING_MOVIE_BY_ID = 'END_FETCHING_MOVIE_BY_ID';